SELECT a.model, t.MONTHID, SUM(flightHours), SUM(flightCycles)
FROM AircraftUtilization au, AircraftDimension a, TemporalDimension t
WHERE au.aircraftID = a.ID AND au.timeID = t.ID
GROUP BY a.model, t.monthID;

SELECT au.AIRCRAFTID, m.Y, SUM(scheduledOutOfService) as ADOSS, SUM(unscheduledOutOfService) as ADOSU
FROM AircraftUtilization au, TemporalDimension t, Months m
WHERE au.timeID = t.ID and t.monthID = m.ID
GROUP BY au.aircraftID, m.y;

SELECT l.MONTHID, a2.MODEL,
	   1000*SUM(l.COUNTER)/SUM(a.FLIGHTHOURS) AS RRh,
	   100*SUM(l.COUNTER)/SUM(a.FLIGHTCYCLES) AS RRc,
	   1000*SUM(CASE WHEN p."ROLE" = 'M' THEN l.COUNTER ELSE 0 END)/SUM(a.FLIGHTHOURS) AS MRRh,
	   100*SUM(CASE WHEN p."ROLE" = 'M' THEN l.COUNTER ELSE 0 END)/SUM(a.FLIGHTCYCLES) AS MRRc,
	   1000*SUM(CASE WHEN p."ROLE" = 'P' THEN l.COUNTER ELSE 0 END)/SUM(a.FLIGHTHOURS) AS PRRh,
	   100*SUM(CASE WHEN p."ROLE" = 'P' THEN l.COUNTER ELSE 0 END)/SUM(a.FLIGHTCYCLES) AS PRRc
FROM LOGBOOKREPORTING l, PEOPLEDIMENSION p, AIRCRAFTUTILIZATION a, AIRCRAFTDIMENSION a2, TEMPORALDIMENSION t 
WHERE l.AIRCRAFTID = a2.ID  AND p.ID = l.PERSONID AND a2.ID = a.AIRCRAFTID  AND t.ID = a.TIMEID
GROUP BY l.MONTHID, a2.MODEL
ORDER BY l.MONTHID;

SELECT a2.MODEL, p.AIRPORT, 1000*SUM(l.Counter)/SUM(a.FLIGHTHOURS) AS MRRh, 100*SUM(l.COUNTER)/SUM(a.FLIGHTCYCLES) AS MRRc
FROM LOGBOOKREPORTING l, PEOPLEDIMENSION p, AIRCRAFTUTILIZATION a, AIRCRAFTDIMENSION a2 
WHERE l.AIRCRAFTID = a2.ID AND p.ID = l.PERSONID AND a2.ID = a.AIRCRAFTID  AND p."ROLE"='M'
GROUP BY a2.MODEL, p.AIRPORT
ORDER BY a2.MODEL, p.AIRPORT;